file(GLOB SHADER_FILES "${SHADER_DIR}/*.vert" "${SHADER_DIR}/*.frag" "${SHADER_DIR}/*.comp")
list(SORT SHADER_FILES)

set(BLOBS "")
set(TABLE "")

foreach(SHADER ${SHADER_FILES})
    get_filename_component(NAME "${SHADER}" NAME)
    string(MAKE_C_IDENTIFIER "${NAME}" SYM)

    file(READ "${SHADER}" HEX HEX)
    string(REGEX REPLACE "(..)" "0x\\1," BYTES "${HEX}")

    string(APPEND BLOBS "static const char emb_${SYM}[] = {${BYTES}0x00};\n")
    string(APPEND TABLE "    {\"shaders/${NAME}\", emb_${SYM}},\n")
endforeach()

set(CONTENT "// Generated by cmake/gen_shaders.cmake -- do not edit.\n#pragma once\n\n${BLOBS}\nstatic const struct { const char* path; const char* src; } embedded_shaders[] = {\n${TABLE}};\n\nstatic const char* embedded_shader_source(const char* path) {\n    for (unsigned i = 0; i < sizeof(embedded_shaders)/sizeof(embedded_shaders[0]); ++i)\n        if (!strcmp(embedded_shaders[i].path, path)) return embedded_shaders[i].src;\n    return 0;\n}\n")

set(OLD "")
if (EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" OLD)
endif()
if (NOT OLD STREQUAL CONTENT)
    file(WRITE "${OUT_FILE}" "${CONTENT}")
endif()
